function com_google_gwt_sample_i18n_I18N(){var l='',B='" for "gwt:onLoadErrorFn"',z='" for "gwt:onPropertyErrorFn"',hc='"><\/script>',D='&',n='/',vb='3C5C0FBF82961342762671C20ABC60E0.cache.html',Db='4552DD26F3B2DB0084D448FE1F8FFEAA.cache.html',pb='4A3AB09767319CE1BB210769603109E4.cache.html',Bb='638A22C7C323B520A0AE2AFB3839CB06.cache.html',qb='6AD01F70C71B014CE5C1AB78E9DB7FFF.cache.html',Ab='7862AE360ECF1C729705D9A78A430B51.cache.html',tb='7F368F6770D4FE33A60ED002CAA71E22.cache.html',Fb='850E657F79499A299CA728EF8F0CD876.cache.html',rb='91458170091E514B6B8B6D196C3F6287.cache.html',wb='9BFABC68A6D6A2BC15AA5B9FF9765072.cache.html',gc='<script id="',fc="<script>com_google_gwt_sample_i18n_I18N.onInjectionDone('com.google.gwt.sample.i18n.I18N')<\/script>",v='=',y='Bad handler "',Cb='D0C35A0853C5826C3153219D2366AB1E.cache.html',ac='DOMContentLoaded',xb='E1B800AA87FD603D16960477FA51ADEF.cache.html',zb='EC96E2E1EE2877415EF2894F032A482D.cache.html',sb='EC9FF40E46EB28AEBA2CE52E52262B0F.cache.html',Eb='F44421D6D6DB3328687FCE9A0EBDFCC9.cache.html',ic='SCRIPT',ab='Unexpected exception in locale detection, using default: ',F='_',dc='__gwt_marker_com.google.gwt.sample.i18n.I18N',o='base',q='clear.cache.gif',m='com.google.gwt.sample.i18n.I18N',u='content',E='default',ub='en',ob='fr',ib='gecko',jb='gecko1_8',nb='gwt.hybrid',A='gwt:onLoadErrorFn',w='gwt:onPropertyErrorFn',t='gwt:property',mb='hosted.html?com_google_gwt_sample_i18n_I18N',hb='ie6',bc='iframe',p='img',cc="javascript:''",C='locale',r='meta',lb='moduleRequested',gb='msie',s='name',db='opera',ec='position:absolute;width:0;height:0;border:none',fb='safari',yb='selectionDone',cb='selectionStart',x='startup',kb='unknown',bb='user.agent',eb='webkit';var kc=window,k=document,sc=kc.external,jc=kc.__gwtstatsEvent?function(a,b,c,d){kc.__gwtstatsEvent(a,b,c,d)}:null,Fc,vc,pc,oc=l,yc={},cd=[],Ec=[],nc=[],Bc,Dc;jc&&jc(m,x,cb,{millis:(new Date()).getTime()});if(!kc.__gwt_stylesLoaded){kc.__gwt_stylesLoaded={}}if(!kc.__gwt_scriptsLoaded){kc.__gwt_scriptsLoaded={}}function uc(){try{return sc&&(sc.gwtOnLoad&&kc.location.search.indexOf(nb)==-1)}catch(a){return false}}
function xc(){if(Fc&&vc){var c=k.getElementById(m);var b=c.contentWindow;b.__gwt_initHandlers=com_google_gwt_sample_i18n_I18N.__gwt_initHandlers;if(uc()){b.__gwt_getProperty=function(a){return qc(a)}}com_google_gwt_sample_i18n_I18N=null;b.gwtOnLoad(Bc,m,oc);jc&&jc(m,x,yb,{millis:(new Date()).getTime()})}}
function rc(){var j,h=dc,i;k.write(gc+h+hc);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=ic){j=j.previousSibling}function d(b){var a=b.lastIndexOf(n);return a>=0?b.substring(0,a+1):l}
;if(j&&j.src){oc=d(j.src)}if(oc==l){var c=k.getElementsByTagName(o);if(c.length>0){oc=c[c.length-1].href}else{var g=k.location;var e=g.href;oc=d(e.substr(0,e.length-g.hash.length))}}else if(oc.match(/^\w+:\/\//)){}else{var f=k.createElement(p);f.src=oc+q;oc=d(f.src)}if(i){i.parentNode.removeChild(i)}}
function Cc(){var f=document.getElementsByTagName(r);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(s),b;if(h){if(h==t){b=e.getAttribute(u);if(b){var i,c=b.indexOf(v);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}yc[h]=i}}else if(h==w){b=e.getAttribute(u);if(b){try{Dc=eval(b)}catch(a){alert(y+b+z)}}}else if(h==A){b=e.getAttribute(u);if(b){try{Bc=eval(b)}catch(a){alert(y+b+B)}}}}}}
function mc(a,b){return b in cd[a]}
function lc(a){var b=yc[a];return b==null?null:b}
function bd(d,e){var a=nc;for(var b=0,c=d.length-1;b<c;++b){a=a[d[b]]||(a[d[b]]=[])}a[d[c]]=e}
function qc(d){var e=Ec[d](),b=cd[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(Dc){Dc(d,a,e)}throw null}
Ec[C]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(C);if(h>=0){var e=b.substring(h);var c=e.indexOf(v)+1;var d=e.indexOf(D);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=lc(C)}if(g==null){return E}while(!mc(C,g)){var f=g.lastIndexOf(F);if(f==-1){g=E;break}else{g=g.substring(0,f)}}return g}catch(a){alert(ab+a);return E}};cd[C]={'default':0,en:1,fr:2};Ec[bb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(db)!=-1){return db}else if(d.indexOf(eb)!=-1){return fb}else if(d.indexOf(gb)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return hb}}}else if(d.indexOf(ib)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return jb}return ib}return kb};cd[bb]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};com_google_gwt_sample_i18n_I18N.onInjectionDone=function(){Fc=true;jc&&jc(m,x,lb,{millis:(new Date()).getTime()});xc()};com_google_gwt_sample_i18n_I18N.onScriptLoad=function(){if(tc){vc=true;xc()}};rc();Cc();var ad;if(uc()){ad=mb}else{try{bd([ob,fb],pb);bd([ob,ib],qb);bd([E,db],rb);bd([E,jb],sb);bd([E,fb],tb);bd([ub,db],vb);bd([ub,jb],wb);bd([ub,fb],xb);bd([E,ib],zb);bd([ub,ib],Ab);bd([ob,db],Bb);bd([ob,jb],Cb);bd([E,hb],Db);bd([ub,hb],Eb);bd([ob,hb],Fb);ad=nc[qc(C)][qc(bb)]}catch(a){return}}var Ac;function zc(){if(!pc){pc=true;xc();if(k.removeEventListener){k.removeEventListener(ac,zc,false)}if(Ac){clearInterval(Ac)}}}
var tc;function wc(){if(!tc){tc=true;var a=k.createElement(bc);a.src=cc;a.id=m;a.style.cssText=ec;a.tabIndex=-1;k.body.appendChild(a);a.contentWindow.location.replace(oc+ad)}}
if(k.addEventListener){k.addEventListener(ac,function(){wc();zc()},false)}var Ac=setInterval(function(){if(/loaded|complete/.test(k.readyState)){wc();zc()}},50);k.write(fc)}
com_google_gwt_sample_i18n_I18N.__gwt_initHandlers=function(i,e,j){var d=window,g=d.onresize,f=d.onbeforeunload,h=d.onunload;d.onresize=function(a){try{i()}finally{g&&g(a)}};d.onbeforeunload=function(a){var c,b;try{c=e()}finally{b=f&&f(a)}if(c!=null){return c}if(b!=null){return b}};d.onunload=function(a){try{j()}finally{h&&h(a)}}};com_google_gwt_sample_i18n_I18N();